import type { Metadata } from "next";
import { Inter_Tight as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import TanstackProviders from "@/components/providers/tanstack-provider";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "INeed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
        <TanstackProviders>{children}</TanstackProviders>
      </body>
    </html>
  );
}
